lejian/user/__init__.py
# -*- coding: UTF-8 -*-
from flask import Blueprint, request
from flask.ext.babel import lazy_gettext as _
import speaklater
from genuine_ap import const
from genuine_ap.basemain import app
from nav_bar import NavBar


user_ws = Blueprint("user-ws", __name__, static_folder="static",
                    template_folder="templates")

user = Blueprint("user", __name__, static_folder="static",
                 template_folder="templates")

from genuine_ap.user.views import user_model_view


from genuine_ap.basemain import register_model_view
sub_nav_bar = NavBar(template=app.jinja_env.get_template('user/nav-bar.html'))
url = speaklater.make_lazy_string(user_model_view.url_for_list,
                                  group=const.VENDOR_GROUP)
sub_nav_bar.register(url, _('Vendor'), enabler=
                     lambda: request.args.get('group', type=int) ==
                     const.VENDOR_GROUP)
url = speaklater.make_lazy_string(user_model_view.url_for_list,
                                  group=const.RETAILER_GROUP)
sub_nav_bar.register(url, _('Retailer'), enabler=
                     lambda: request.args.get('group', type=int) ==
                     const.RETAILER_GROUP)
url = speaklater.make_lazy_string(user_model_view.url_for_list,
                                  group=const.SUPER_ADMIN)
sub_nav_bar.register(url, _('Administrator'), enabler=
                     lambda: request.args.get('group', type=int) ==
                     const.SUPER_ADMIN)

for model_view in [user_model_view]:
    register_model_view(model_view, user,
                        list_view={'sub_nav_bar': sub_nav_bar})

lejian/user/views.py
# -*- coding: UTF-8 -*-
from flask import (jsonify, request, render_template, redirect, session,
                   current_app)
from flask.ext.wtf import Form
from flask.ext.babel import _, lazy_gettext
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired
from werkzeug.security import generate_password_hash
from flask.ext.login import (current_user, login_user, login_required,
                             logout_user)
from flask.ext.principal import Identity, AnonymousIdentity, identity_changed
from flask.ext.databrowser import ModelView, filters, sa, extra_widgets
from flask.ext.databrowser.col_spec import (InputColSpec, ColSpec,
                                            InputHtmlSnippetColSpec)
from flask.ext.databrowser.action import DeleteAction
from flask.ext.principal import Permission

from genuine_ap.user import user_ws, user
from genuine_ap.models import User, Group
from genuine_ap import utils, apis, const
from genuine_ap.exceptions import AuthenticateFailure
from genuine_ap.database import db


@user_ws.route('/register', methods=['POST'])
def register_ws():
    name = request.args.get("name", type=str)
    password = request.args.get("password", type=str)
    if not name or not password:
        return u"需要name或者password字段", 403

    user = User.query.filter(User.name == name).first()
    if user:
        return u'用户名已存在, 请更换注册名', 403
    user = utils.do_commit(User(name=name,
                                password=generate_password_hash(
                                    password, 'pbkdf2:sha256'),
                                group=Group.query.get(const.CUSTOMER_GROUP)))
    user = apis.wraps(user)
    return jsonify(user.as_dict(include_auth_token=True)), 201


@user_ws.route("/login", methods=["POST"])
def login_ws():
    name = request.args.get("name", type=str)
    password = request.args.get("password", type=str)
    if not name or not password:
        return u"需要name或者password字段", 403
    try:
        user = apis.user.authenticate(name, password)
    except AuthenticateFailure:
        return u'用户名或者密码错误', 403
    return jsonify(user.as_dict(include_auth_token=True))


class LoginForm(Form):

    username = TextField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])


@user.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == "GET":
        if current_user.is_anonymous():
            return render_template("user/login.html", form=form, error=request.args.get("error"),
                                   next=request.args.get("next"))
        return redirect("/")
    else:
        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            try:
                user = apis.user.authenticate(username, password)
            except AuthenticateFailure:
                return render_template("user/login.html",
                                       error=u"用户名或者密码错误", form=form), 403
            if not login_user(user):
                return render_template("user/login.html",
                                       error=u"登陆失败"), 403

            identity_changed.send(current_app._get_current_object(),
                                  identity=Identity(user.id))
            return redirect(request.args.get('next', "/"))
        return render_template("user/login.html",
                               error=u"请输入用户名及密码", form=form), 403


@user.route("/logout")
@login_required
def logout():
    try:
        logout_user()
    except Exception:  # in case sesson expire
        pass
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)

    identity_changed.send(current_app._get_current_object(),
                          identity=AnonymousIdentity())
    next_url = request.args.get("next", "/")
    return redirect(next_url)


class UserModelView(ModelView):

    list_template = 'user/list.html'

    @property
    def sortable_columns(self):
        return ['id', 'create_time', "name", "vendor", "retailer"]

    @property
    def filters(self):
        return [
            filters.Contains('name', self, label=_('name'), name=_('contains')),
            filters.EqualTo('group', self, label=_('group'), name=_('is'),
                            hidden=True),
        ]

    @property
    def list_columns(self):
        return [
            ColSpec('id', _('id')),
            ColSpec('name', _('name')),
            ColSpec('group', _('group')),
            ColSpec('create_time', _('create time'), formatter=lambda v, obj:
                    v.strftime('%Y-%m-%d %H:%M')),
            ColSpec('vendor', _('vendor')),
            ColSpec('retailer', _('retailer'))
        ]

    @property
    def create_columns(self):
        return [
            InputColSpec('name', _('name')),
            InputHtmlSnippetColSpec('password', label=_('password'),
                                    template=
                                    'data_browser__/snippets/password.html',
                                    render_kwargs={'encrypt_method':
                                                   'pbkdf2:sha256'}),
            InputColSpec('group', _('group'), filter_=lambda q:
                         q.filter(Group.id != const.CUSTOMER_GROUP)),
        ]

    @property
    def edit_columns(self):
        return [
            InputColSpec('id', _('id'), disabled=True),
            InputColSpec('create_time', _('create time'), disabled=True),
            InputColSpec('name', _('name')),
            InputHtmlSnippetColSpec('password', label=_('password'),
                                    template=
                                    'data_browser__/snippets/password.html',
                                    render_kwargs={'encrypt_method':
                                                   'pbkdf2:sha256'}),
            InputColSpec('group', _('group'), filter_=lambda q:
                         q.filter(Group.id != const.CUSTOMER_GROUP)),
        ]

    def get_actions(self, processed_objs=None):
        class _DeleteAction(DeleteAction):

            def test(self, *objs):
                if any(obj.group_id == const.SUPER_ADMIN for obj in objs):
                    return 1
                elif any(obj.retailer for obj in objs):
                    return 2
                elif any(obj.vendor for obj in objs):
                    return 3
                return super(_DeleteAction, self).test(*objs)

            @property
            def forbidden_msg_formats(self):
                ret = super(_DeleteAction, self).forbidden_msg_formats
                ret[1] = _("you can't remove administrator account %%s!")
                ret[2] = _('user %%s has retailer, remove the retailer '
                           'at first!')
                ret[3] = _('user %%s has vendor, remove the vendor as first1')
                return ret

        return [_DeleteAction(_("remove"))]


user_model_view = UserModelView(sa.SAModell(User, db, lazy_gettext('User')))

lejian/templates/user/list.html
{% extends "data_browser__/list.html" %}

{% block body %}
<div class="row">
  {{ sub_nav_bar.as_ul(highlight_class='active')|safe }}
</div>
<div class="row">
    {% block lists %} 
      {{ super() }}
    {% endblock %}
    <div class="col-lg-2">
      {% block filters %}
        {{ super() }}
      {% endblock filters %}
    </div>
</div>
{% endblock %}

lejian/templates/user/login.html
{% extends "layout.html" %}

{% block __data_browser__title_block %}
  360真品 - 登录
{% endblock %}

{% block body %}
  <div class="container">

    <form action="{{ url_for("user.login") }}" role="form" class="alert alert-info form-horizontal form-signin" method="POST">

      <div>
       <h4>请登录：</h4>
      </div>
      <hr/>
      {% if error %}
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ error }}
        </div>
      {% endif %}
      {{ form.csrf_token }}

      <div class="form-group">
        <label class="sr-only">登录</label>
        <div class="input-group col-lg-12">
          <span class="input-group-addon">
            <i class="fa fa-user fa-fw"></i>
          </span>
          <input type="text" name="username" id="username" required="required" placeholder="用户名" class="form-control"/>
        </div>

      </div>
      <div class="form-group">
        <label class="sr-only">密码</label>
        <div class="input-group col-lg-12">
          <span class="input-group-addon">
            <i class="fa fa-fw fa-keyboard-o"></i>
          </span>
          <input type="password" name="password" id="password" required="required" placeholder="密码" class="form-control"/>
        </div>
      </div>
      <hr>
      <div class="form-group">
        <div class="col-lg-12">
          <button class="btn btn-block btn-lg btn-success">
            <i class="fa fa-sign-in fa-fw fa-lg"></i>登录
          </button>
        </div>
      </div>
      {% if next %}
        <input type="hidden" name="next" value="{{ next }}">
      {% endif %}
    </form>
  </div>
{% endblock %}

lejian/templates/user/nav-bar.html
<ul class="nav nav-tabs">
    {% for nav_link in nav_links %}
      {% if nav_link.enabler() %}
        <li class="{{ highlight_class }}">
          <a href="{{ nav_link.url }}">
            <strong>{{ nav_link.anchor }}</strong>
          </a>
        </li>
      {% else %}
        <li class="{{ normal_class }}">
          <a href="{{ nav_link.url }}">{{ nav_link.anchor }}</a>
        </li>
      {% endif %}
    {% endfor %}
</ul>